# DI PYTHON HACKATON MAY 2021 - Ecology quizzes - A Scrapy Experiment 
# Created on  : 210523 by : lidu
# Modified on : 210524 by : lidu

import json
import sqlite3 as sl

# Loading quizzes.db with quizz.json file generated by Scrapy

# 1. Read from json file
with open('./quizzscraper/quizz.json') as f:
    data = json.load(f)

# 2. Write to sqlite3 database
connection = sl.connect('quizzes.db')
cursor = connection.cursor()
# Data about this particular quizz
query = '''INSERT INTO quizz ("name", "source", "scrapy_criteria") VALUES ("Ecology Trivia", "https://www.triviaquestionquiz.com/ecology-trivia-questions/", "response.css('div.wq-question')");'''
query_result = cursor.execute(query)
qid = 0
for qa in data:
    quizz_id = 1
    qid += 1
    question = qa['question']
    query = f"INSERT INTO question ('text', 'quizz_id') VALUES ({repr(question)},{quizz_id});"
    query_result = cursor.execute(query)
    counter = 0
    for answ in qa['answers']:
        counter += 1
        correct = (counter == qa['correct'])
        query = f"INSERT INTO answer ('text', 'correct', 'question_id') VALUES ({repr(answ)},{correct},{qid});"
        query_result = cursor.execute(query)
    
connection.commit()
connection.close()